### ISSUE TITLE
Comment fences

### ISSUE THREAD

**Issue by garethrees** [rubocop-hq/ruby-style-guide#115]
I tend to separate methods in to logical groups, somewhat like using `context` blocks in tests. For example:

``` ruby
class Cart

  # ==========================
  # Add / Remove Items
  # ==========================

  def add(item)
    # ...
  end

  def remove(item)
    # ...
  end

  # ==========================
  # Calculate Totals
  # ==========================

  def total
    # ...
  end

  def total(item)
    # ...
  end
end
```
- Is there a standard for this type of comment fencing?
- Should you even do this? I find it helps on larger classes (although there is the case for presenters / modules etc)
#### Proposed style:
- Dividers should start at the same level of indentation as the methods they are fencing
- Dividers should start with `#`, followed by one space, followed by `=` up to 80 characters
- `=` should extend to column 80, regardless of starting point
- There should be no line breaks between the fences and the title inside them
- Titles should be on one line only
###### Example:

``` ruby
class Noises

  # BAD

  # ============
  # Angry Noises
  # ============

  def blah

  end

  # GOOD

  # ===========================================================================
  # Angry Noises
  # ===========================================================================

  def blah

  end

  module Something

    # =========================================================================
    # Does not exceed 80 characters
    # =========================================================================

    def higher_indentation

    end

  end

end
```

Open to feedback and suggestions

**Comment by keygen-maker** [comment]
Fences  automatically organizes icons for desktop shortcuts and playback functions.Customize the spacing between icons and fences.: it stores your drawings, files and folders in a shaded area, which can be hidden with a simple double click, and it even creates a desktop page that you can easily view. 
Bobby
keygenbro.com

**Comment by khansa608** [comment]
Fences Serial Key automatically customize the layout of your office shortcuts and workflow. Automatically adjust the course of the board, collect your shadow area, hide with a simple double click and much more. 
Michelle
patchhere.com
