### ISSUE TITLE
Naming & Comments : Use English only

### ISSUE THREAD

**Issue by ghost** [rubocop-hq/ruby-style-guide#137]
Maybe some people will disaggree but, being a French programmer, I consider that using English only for naming and commenting things should be a rule.

It could seem useless for non-English projects but ruby doesn't seem to appreciate special characters in the code (even in comments), and evereybody knows that "special characters" means "non English ones".

Using English only protects from some execution errors, in addition to compatibility with Rails `singularize` and `pluralize` methods (but this is not a Ruby concern).

**Comment by coreyward** [comment]
Adherence to this rule also prevents the use of non-ASCII symbols that are proper English, such as en and em dashes, real quotes, many mathematical symbols, and emoji (😲 ). While this may be a technical limitation for some languages, it isn't for Ruby.
