### ISSUE TITLE
Alignment of assignments

### ISSUE THREAD

**Issue by lenntt** [rubocop-hq/ruby-style-guide#186]
Keeping my lines short, I sometimes end up having some local variables
I wonder what other people think about:

```
foo = 3
bar_var = 4
foobar_var = foo + bar_var
very_long_variable =
   need_to_use a_new_line
baz = foo / foobar_var
```

vs 

```
foo                = 3
bar_var            = 4
foobar_var         = foo + bar_var
very_long_variable = need_to_use
                     a_new_line
baz                = foo / foobar_var
```

and 

```
foo = 
```

I think you can have the same discussion on alignmnent of hash keys/values.

The style guide doesn't say much about this. 
I prefer the second one, but there may be exceptions  (e.g. when one variable name is very long and other assignments are long).
What do you think?

**Comment by dominh** [comment]
Is this cop already implemented?
