### ISSUE TITLE
Use then instead of ; for case

### ISSUE THREAD

**Issue by agrimm** [rubocop-hq/ruby-style-guide#21]
The chapter "The Ruby language" of "Programming Ruby 1.9" doesn't document the use of semicolons for case expressions - it only mentions `then`. It may be syntactically valid, but it's so unusual that it shouldn't be used. Semicolons should only exist when they're being used to put multiple lines of code on a single line, and it should be rare enough that it's a code smell. If semicolons are regularly used, then they don't leap out as a warning that your code smells.

**Comment by ccutrer** [comment]
I don't see that semicolons were ever deprecated. Colons were (most likely) removed due to syntactic ambiguity with 1.9 style hashes. can we get this updated to be an option A or option B like other areas of the style guide?
