### ISSUE TITLE
How about them hashes as method parameters?

### ISSUE THREAD

**Issue by chuckxD** [rubocop-hq/ruby-style-guide#243]
I am often surprised that no one else has raised any questions on the right thing to do whenever dealing with methods that take hashes as arguments or conventions whenever dealing with nested hashes, but more specifically, I wanted to gather your opinions whenever dealing with find in the the ruby mongodb driver.

Here are a couple examples I find bothersome:

``` ruby
      @retailer.profiles.find({
          :_id => { "$in" => @views_slice.keys },
          :email => { "$exists" => true },
        },
        { :fields => ["_id", "email", "purchases"] }).to_a
```

And I tend to do this on a regular basis even though it's more or less the convention I've settled on at work. Although assignments will muck up readability a bit:

``` ruby
      emails_with_views = @retailer.profiles.find({
          :_id => { "$in" => @views_slice.keys },
          :email => { "$exists" => true },
        },
        { :fields => ["_id", "email", "purchases"] }).to_a
```

I think this is a little better, but by not much:

``` ruby
      emails_with_views =
        @retailer.profiles.find({
          :_id => { "$in" => @views_slice.keys },
          :email => { "$exists" => true }
        },
        { :fields => ["_id", "email", "purchases"] }).to_a
```

I honestly feel like this the right convention in ruby and mongodb, but I've ran into enough people that disagree with me so I don't do it and am yet somewhat flabbergasted at how many from ruby don't like it:

``` ruby
      @retailer.profiles.find(
        { :_id => { "$in" => @views_slice.keys },
          :email => { "$exists" => true } },
        { :fields => ["_id", "email", "purchases"] }
      ).to_a
```

I won't care but Mother of Mary forgive thee, if you do this:

``` ruby
      @retailer.profiles.find({ :_id => { "$in" => @views_slice.keys }, :email => { "$exists" => true } },
                              { :fields => ["_id", "email", "purchases"] }).to_a
```

In my heart I will curse you into 1000 suns if I see something like this, even if everyone agrees this is correct.

``` ruby
@retailer.profiles.find(
        {
          :_id => {
            "$in" => @views_slice.keys
          },
          :email =>
          {
            "$exists" => true
          }
        },
        { :fields => ["_id", "email", "purchases"] }).to_a

```

and RIP in peace if you ever do this:

``` ruby
      @retailer.profiles.find({ :_id => { "$in" => @views_slice.keys }, :email => { "$exists" => true } }, { :fields => ["_id", "email", "purchases"] }).to_a
```

Which is what I unfortunately see more often than I'd like. I didn't want to submit a PR until I at least discussed it and gathered some additional insights and opinions regarding this "build your arguments as hashes in your method call" convention. 

Building your hash as an assignment outside of the method for some reason feels out of the question and awkward at most times. I feel like the best balance in dealing with this convention can be borrowed from how you guys define multi-line parameters as arguments in methods and multi-line literals in array assignments... but, but then how come no multi-line (often nested) hash assignment literal assignment setting convention?

So as of lately, as inactive in the community as I might be, and since I am already here composing this issue, here is what my heart says:

``` ruby
      @retailer.profiles.find({ :_id => { "$in" => @views_slice.keys },
                                :email => { "$exists" => true }
                              }, 
                              { :fields => ["_id", "email", "purchases"] }).to_a

```

Add an assignment:

``` ruby
      profiles_with_email =
        @retailer.profiles.find({ :_id => { "$in" => @views_slice.keys },
                                  :email => { "$exists" => true }
                                },
                                { :fields => ["_id", "email", "purchases"] }).to_a
```

I find this even more endearing, although a little harder to read:

``` ruby
      profiles_with_email =
        @retailer.profiles.find({ :_id => { "$in" => @views_slice.keys },
                                  :email => { "$exists" => true } },
                                { :fields => ["_id", "email", "purchases"] }).to_a
```

My vim has never appreciated closing the curly brace on the first hash but feel like this is something that can be dealt with separately. Lastly, how does this make you feel?

``` ruby
      emails_with_views =
        @retailer.profiles.find(
          { :_id => { "$in" => @views_slice.keys },
            :email => { "$exists" => true } },
          { :fields => ["_id", "email", "purchases"] }
        ).to_a
```

**Comment by pirj** [comment]
Closing as stale.
https://github.com/rubocop-hq/ruby-style-guide#method-arguments-alignment partially addresses this question.
