### ISSUE TITLE
Multi-line lambdas cause syntax error with scope

### ISSUE THREAD

**Issue by ResumeNothing** [rubocop-hq/ruby-style-guide#270]
Per http://stackoverflow.com/questions/1476678/rails-named-scope-lambda-and-blocks

The following causes a syntax error:

``` ruby
named_scope :admin, lambda do |company_id| 
  {:conditions => ['company_id = ?', company_id]}
end
```

There are a couple workarounds involving parens:

``` ruby
named_scope :admin, (lambda do |company_id| 
  {:conditions => ['company_id = ?', company_id]}
end)

named_scope(:admin, lambda do |company_id| 
  {:conditions => ['company_id = ?', company_id]}
end)
```

However, I can't help but feel that both of these are inferior to:

``` ruby
named_scope :admin, ->(company_id) do 
  {:conditions => ['company_id = ?', company_id]}
end
```

Note that example just happens to have arguments; the syntax error with the lambda method occurs when there are no arguments as well.

**Comment by paulwalker** [comment]
In general, class macros should always have a preferred multi-line syntax. While there is a reasonable alternative in this case, that is not always guaranteed.

**Comment by martinverdejo** [comment]
@bbatsov how would you resolve a trivial scenario with `join().where()` given that [you also suggest having 80 characters per line](https://github.com/bbatsov/ruby-style-guide#80-character-limits), which implies writing a multi-line scope?

**Comment by ACPK** [comment]
@ResumeNothing - How would you recommend refactoring:

    scope :latest, -> { order('date DESC') }

**Comment by ResumeNothing** [comment]
@ACPK: I don't really see anything there that needs refactoring. It looks fine as-is to me.

**Comment by ACPK** [comment]
@ResumeNothing - Robocop was saying it's incorrect. I don't have the error in front of me at the moment.

**Comment by ResumeNothing** [comment]
If you just want to get rid of the error this should work:

```ruby
scope :latest, (-> { order('date DESC') })
```

The syntax you're using, however, is okay, and should be supported in not-so-distant version of rubocop: https://github.com/bbatsov/rubocop/pull/4237.

**Comment by ACPK** [comment]
@ResumeNothing ok, thanks!
