### ISSUE TITLE
First letter capitalized in comments

### ISSUE THREAD

**Issue by dwbutler** [rubocop-hq/ruby-style-guide#297]
Should the style guide explicitly specify that the first letter in a comment should be capitalized? Personally, I would consider the first letter in a comment to be the same as the first letter in a sentence, and therefore should be capitalized.

Another way of saying it is that comments that are sentences should be styled the same way as sentences:

```
# First letter capitalized, period at the end.
```

I see this rule being followed in the wild. To pick a random example from Devise:

https://github.com/plataformatec/devise/blob/master/lib/devise/mapping.rb

``` ruby
    # Receives an object and find a scope for it. If a scope cannot be found,
    # raises an error. If a symbol is given, it's considered to be the scope.
    def self.find_scope!(obj)
      case obj
      when String, Symbol
        return obj
      when Class
        Devise.mappings.each_value { |m| return m.name if obj <= m.to }
      else
        Devise.mappings.each_value { |m| return m.name if obj.is_a?(m.to) }
      end

      raise "Could not find a valid mapping for #{obj.inspect}"
    end

    # Return modules for the mapping.
    def modules
      @modules ||= to.respond_to?(:devise_modules) ? to.devise_modules : []
    end
```

**Comment by bbatsov** [comment]
I guess we solved it already https://rubystyle.guide/#english-syntax
