### ISSUE TITLE
We should discard the "Write comments in English" rule.

### ISSUE THREAD

**Issue by yorkxin** [rubocop-hq/ruby-style-guide#301]
I found this rule was first added in #137. As a Ruby developer who use Chinese as a native language, I disagree this rule.

Maybe the old Rubies does not accept non-ascii chars at all, but today the MRI 2.0 (even 1.9) are already UTF-8-aware, so there is no reason to limit to ASCII today.

The reason I take a look at this is that, I started using Rubocop today, and it by default forces my Ruby code use US-ASCII in comments. While I am working at a team in Taiwan, we use Chinese as our working language, so it is very common that we write comments in Chinese, because that's our native language.

Therefore, I think there is no more need to have this rule: "Write comments in English." However it is always good to keep the comments readable as a documentation, so instead I suggest it should be "Write comments in native language."

**Comment by schmijos** [comment]
This is not only a language thing. I stumbled over this when commenting what parameters a Rails API action gets from the outside (I'm not using all of them):

```
# The parameters this action can get from Datatrans are the following:
# {… "utf8"=>"✓", …}
```

**Comment by jdickey** [comment]
@schmijos I'd then argue for a `#rubocop:disable AsciiComments` fence around the block of code containing such a comment. *In the specific context you describe,* the rule may be a pain, but getting rid of it entirely sends the message that developers whose native language is not the one being used for comments are not welcome to contribute. (I'm functionally literate in over half a dozen human languages, just in case people were thinking of throwing around the "ugly American" meme.) I have recently led a development team spread across six countries and four native languages that shipped a revenue product; people on that team often started pairing using a different language, and then realised that constantly switching back and forth between, say, Tiếng Việt and English when you need to work with people in other locations, simply isn't worth the additional cognitive load.

**Comment by emre-basala** [comment]
Allowing currencies can be a good idea, currently, if we want to add a comment like "we store £2.00 as 200 " etc, you need to disable the rule.
