### ISSUE TITLE
Multi-line comment spacing inconsistency

### ISSUE THREAD

**Issue by fishermand46** [rubocop-hq/ruby-style-guide#352]
The rule about multi-line comments says: "If multiple lines are required to describe the problem, subsequent lines should be indented two spaces after the #"

However, in the example:

``` ruby
# FIXME: This has crashed occasionally since v3.2.1. It may
#   be related to the BarBazUtil upgrade.
```

the second line is indented three spaces after the #.

**Comment by fishermand46** [comment]
Any thoughts on this? Should it read "three spaces after the #" or should the example be intended two spaces?

**Comment by LavirtheWhiolet** [comment]
:+1: to @fishermand46.

**Comment by bbatsov** [comment]
Indeed. I guess we just made a typo with the example.

**Comment by tejasbubane** [comment]
@bbatsov I think this has been fixed in https://github.com/rubocop-hq/ruby-style-guide/pull/346.
