### ISSUE TITLE
Ruby 2.1 Features like Named Parameters

### ISSUE THREAD

**Issue by justin808** [rubocop-hq/ruby-style-guide#396]
How about something in regards to:

Use named parameters in the following cases:
1. When a method takes 2 booleans, so rather than calling `calculate(true, false)`, call `calculate(optimized: true, debug: false)`.
2. When a method has more than 3 parameters.

**Comment by bbatsov** [comment]
I think we already have a few rules dedicated to keyword params, so I'll close this one.
