### ISSUE TITLE
Use double indent when continuing a line onto a second

### ISSUE THREAD

**Issue by fishermand46** [rubocop-hq/ruby-style-guide#403]
I find it helpful to use a double indent when continuing a line onto a second line, so as to distinguish it from a normal start-of-block indentation.

``` ruby
really.long.complex.line && more + stuff
    || this - stuff

normal_block.each do |item|
  puts stuff
end
```

What do you guys think?

**Comment by dpisarewski** [comment]
I guess majority of IDEs makes double indent for continuation by default.

**Comment by pirj** [comment]
Closing as stale.
