### ISSUE TITLE
Don't use FixNum and BigNum classes for type checking.

### ISSUE THREAD

**Issue by dpisarewski** [rubocop-hq/ruby-style-guide#405]
The problem is that `FixNum` is a platform-dependent type. Ruby automatically switches from `FixNum` to `BigNum` if the number becomes bigger than native integer(which has different length on 32-bit and 64-bit platforms). So if you just want to check whether it's an integer you should use `Integer` for it.

For example:

``` ruby
timestamp = Time.now.to_i

#bad
timestamp.is_a? FixNum
timestamp.is_a? BigNum

#good
timestamp.is_a? Integer
```

Please take a look at the issue from neo4j gem https://github.com/neo4jrb/neo4j/issues/663.

**Comment by bbatsov** [comment]
I'm OK with adding a rule regarding this.

**Comment by bbatsov** [comment]
I guess this was solved by itself now that Ruby unified those classes. :-)
