### ISSUE TITLE
No guidance regarding preferential use of `(&:method)` ?

### ISSUE THREAD

**Issue by NewAlexandria** [rubocop-hq/ruby-style-guide#419]
I notice that there is no mention of the use of `(&:method)`

I see this pattern regularly, and have always thought of it as a best practice.  Can we add a section for it?

``` ruby
# bad
things.map { |thing| thing.some_method }

# good
things.map(&:some_method)

```

**Comment by maasha** [comment]
Rubocop says:

    test.rb:3:1: C: Pass &:some_method as an argument to map instead of a block.
    things.map { |thing| thing.some_method }
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Which makes be believe it is already in the style guide?

**Comment by philoserf** [comment]
Not all in rubocop is in the style guide. Thus only guide cops option.

https://github.com/bbatsov/rubocop/blob/master/lib/rubocop/options.rb

**Comment by maasha** [comment]
And why are not all cop actions from the style guide? I would expect that perhaps cop actions was missing, but not the other way around.

**Comment by bbatsov** [comment]
> And why are not all cop actions from the style guide? I would expect that perhaps cop actions was missing, but not the other way around.

People submitted pretty sensible cops and they got merged. I forgot to update the guide accordingly.

**Comment by pirj** [comment]
Covered in https://github.com/rubocop-hq/ruby-style-guide#proc-application-shorthand
