### ISSUE TITLE
TomDoc or Yard instead of Rdoc

### ISSUE THREAD

**Issue by maasha** [rubocop-hq/ruby-style-guide#420]
The style-guide says:

```
Use RDoc and its conventions for API documentation.
```

However, the lack of consistent structure and readability in RDoc have lead to the specification of TomDoc. The style-guide should perhaps encourage TomDoc (optional)?

Here is some relevant reading:

http://tom.preston-werner.com/2010/05/11/tomdoc-reasonable-ruby-documentation.html
http://gnuu.org/2010/05/12/whats-missing-from-tomdoc/
http://tomdoc.org/

**Comment by bbatsov** [comment]
Or we can just remove this. I don't think many people use TomDoc these days. Yard is pretty popular, though.

**Comment by sfcgeorge** [comment]
* (possibly biassed) blog post from creator of YARD on TomDoc's shortcomings: http://gnuu.org/2010/05/12/whats-missing-from-tomdoc/
* YARD has a nicer syntax than RDoc that will be familiar to developers coming from other languages. It is actively developed too unlike TomDoc.
* There is actually a [TomDoc plugin](https://github.com/rubyworks/yard-tomdoc) for YARD, for best of both worlds.
* YARD powers rubydoc.info which automatically documents github projects and gems.

So my vote is changing to say YARD.

**Comment by Ch4s3** [comment]
+1 for YARD

**Comment by philoserf** [comment]
+ for YARD

My unscientific examination of the community repos show very little Tomdoc in the wild and much Yard.

**Comment by snowe2010** [comment]
+1 for YARD, TomDoc is a very one sided view for documentation. Yard is a much better choice.

**Comment by onebree** [comment]
+1 for YARD. I only heard about TomDoc toady, when browsing Github's internal style guides. I see YARD almost always in the wild.

I agree with @bbatsov in that it should just be removed.

**Comment by arbox** [comment]
I would encourage people to use YARD.

**Comment by lazybios** [comment]
same as @onebree  just see TomDoc in Github internal style guides. +1 for YARD

**Comment by bbatsov** [comment]
PRs welcome. :-)
