### ISSUE TITLE
Recommendation to remove prefixes "get_" and "set_" from method names

### ISSUE THREAD

**Issue by ASnow** [rubocop-hq/ruby-style-guide#423]
Redundant style. This prefixes should not be used instead of accessors. The only one sample where I can imagine usage of this prefixes is DSL methods or IO interaction(getchar)

**Comment by MathieuAA** [comment]
get_ and set_ should not be encouraged (except in a few cases).
One can always replace the object's accessor with his/her own anyway...
It's just that it's better not to use any get_x/set_x, as a newbie first and as someone used to Ruby's syntax and readability (it's nicer to read object.attribute/= than object.(get/set)_attribute).

**Comment by Ajedi32** [comment]
I think the real takeaway is to not use `get_*` and `set_` when the getter method takes no arguments, or when the setter method only takes one argument.

For example, look at the way Rails uses methods with get and set in their names. (Search for "get_" and "set_" on <api.rubyonrails.org>). None of those uses are inappropriate IMO.

**Comment by onebree** [comment]
To clarify, you are saying to never make a method names `get_*`? In the company app, we have some that are called `get_*`, but they get things like the params and manipulate them into a hash.. Or make calls to other DBs that are not associated with ActiveRecord.

**Comment by MathieuAA** [comment]
I agree with you, @Ajedi32. The case you mentionned is one of the few cases where get_* and set_* are useful as name prefixes.
And, I agree with you too @onebree, get_* is justified (you just don't access something, you call a method that does some actions behind the scenes, etc.). In this case, get_*/set_* may be OK.

**Comment by Ajedi32** [comment]
So to distill this even further, what's really meant here is that you shouldn't use `get_xxx` or `set_xxx` as accessors for attributes on objects when `xxx` and `xxx=` would work. Seems like the kind of mistake that might be made by those new to Ruby, coming from another language like Java.

Not quite sure on the best way to word that.

**Comment by MathieuAA** [comment]
This looks to me the kind of mistake a Java user would make (always use getXXX for an 'attribute' when one can do `instance.field`). That, or I'm not sure I get what you say.
And, yes `xxx` and `xxx=` would 'work', but more than that: this is the way Ruby makes an instance variable accessible (by way I mean syntax).

**Comment by onebree** [comment]
@Ajedi32 I think that is an appropriate thing to note in the style guide. The guide should enforce not using `get`/`set` prefixes when you can easily use `attr=` or something of the like.

**Comment by pirj** [comment]
Covered in https://github.com/rubocop-hq/ruby-style-guide#accessormutator-method-names
