### ISSUE TITLE
Using next when skipping first iteration in a loop

### ISSUE THREAD

**Issue by snowe2010** [rubocop-hq/ruby-style-guide#448]
I understand the logic behind using next if skipping in a loop, but what about if you are _always_ skipping the first loop. I have this code:

```
procedure_entered_element.drop(1).each do |r|
  (do stuff on every single loop except the first)
end
```

and we never ever want to hit the first loop as it's just the heading information in an html table. 
What we have been doing is using drop(1), and it's significantly faster than using next.

```
Benchmark.ips do |x|
  arr = (0..200_000).to_a.shuffle
  x.report("drop") { arr.drop(1).each {|i| i} }
  x.report("next") { arr.each_with_index {|k, i| next if i == 0; k } }
  x.report("slice"){ arr[1..-1].each {|i| i} }
  x.compare!
end
Calculating -------------------------------------
                drop     9.000  i/100ms
                next     5.000  i/100ms
               slice     9.000  i/100ms
-------------------------------------------------
                drop     97.826  (± 1.0%) i/s -    495.000
                next     54.091  (± 1.8%) i/s -    275.000
               slice     97.189  (± 2.1%) i/s -    486.000

Comparison:
                drop:       97.8 i/s
               slice:       97.2 i/s - 1.01x slower
                next:       54.1 i/s - 1.81x slower
```

Should the cop/rules be changed to allow this?

**Comment by onebree** [comment]
In my opinion, this is too specific of a case to include in the style guide.

**Comment by snowe2010** [comment]
Probably should have just filed it with Rubocop then, but it's here now so I'll wait to here what @bbatsov has to say about it.

**Comment by scudelletti** [comment]
I really liked your approach using `drop`. However I agree with @onebree. :smile:

**Comment by pirj** [comment]
Closing as stale.
