### ISSUE TITLE
Use RDoc and its conventions for API documentation.

### ISSUE THREAD

**Issue by maxcal** [rubocop-hq/ruby-style-guide#455]
I don't really think this guide needs to be opinionated on RDoc vs YARD vs Whatever. The main point is that your should document your API's and while doing so follow the conventions of the documentation tool.

**Comment by philoserf** [comment]
:+1: @maxcal

**Comment by jdickey** [comment]
:+1: to that as well. RDoc was adequate in the days when JavaDoc was new and shiny; the world *has* moved on.

**Comment by bbatsov** [comment]
Yeah, I'm fine with dropping this and replacing it with some generic guidelines about API documentation.
