### ISSUE TITLE
Spacing default parameters in method definitions

### ISSUE THREAD

**Issue by trliner** [rubocop-hq/ruby-style-guide#52]
Can we build consensus behind whether to use spaces around `=` when assigning a default value to a method parameter?

For example:

```
def method_one(arg1=:default, arg2=nil, arg3=[])
  # do something...
end
```

vs.

```
def method_two(arg1 = :default, arg2 = nil, arg3 = [])
  # do something...
end
```

I vote for leaving out the spaces as in `method_one`.

**Comment by Ajedi32** [comment]
Personally I prefer `method_one` because it visually groups parameters together with their defaults, but fair enough...
