### ISSUE TITLE
Using assignment in an if statement

### ISSUE THREAD

**Issue by amiel** [rubocop-hq/ruby-style-guide#53]
One of the reasons people don't like using assignment within if statements is because of how common it is for

There's a convention I've used to make it clear that the assignment is intentional:

``` ruby
  # Intentional assigment
  if (v = array.grep(/foo/))
    ...
  end

  # Oops, this should be equality
  if v = 1
    ...
  end
```

I like this because it sort of separates the assignment from the conditional, and clarifies the intention.

What do y'all think?

**Comment by pauldraper** [comment]
@tokland, should be

> If blue the sky is

Most often, I find the analogous Yoda syntax to be postfix.
