### ISSUE TITLE
Guidelines to use blocks as source of message for Logging

### ISSUE THREAD

**Issue by srikanthps** [rubocop-hq/ruby-style-guide#540]
As documented in [Impact of logs on performance](http://guides.rubyonrails.org/debugging_rails_applications.html#impact-of-logs-on-performance), one should prefer to pass a block to logger methods so that strings are evaluated lazily.

```
 # bad
 logger.debug "Person attributes hash: #{@person.attributes.inspect}"

 # good
 logger.debug {"Person attributes hash: #{@person.attributes.inspect}"}
```

Should above be added as one of the guidelines for Ruby style?

**Comment by bbatsov** [comment]
I think not, as that's too specific to a particular logging framework.
