### ISSUE TITLE
Method Call on Multiple Lines

### ISSUE THREAD

**Issue by rrennie6** [rubocop-hq/ruby-style-guide#542]
If a method call gets too long for a single line, does it seem reasonable to say that this is the correct way to go about shortening the line?

 # bad
do_method(
    param_1, param_2, param_3
)  

 # good (imagine the parameters are lined up)
do_method(param_1,
           param_2,
           param_3)

Should above be added as one of the guidelines for Ruby style?

**Comment by dakull** [comment]
@rrennie6 

I usually go for

```ruby
ruby_method(
  param_1,
  param_2,
  param_3
)
```

**Comment by davidsoncasey** [comment]
I agree with @dakull, if I split a method call across multiple lines I like to make it clear by putting the first argument on a new line, and using the closing parenthesis to match the indentation of the method name.

**Comment by jdickey** [comment]
I _really_ don't like the closing parenthesis on a line by itself, especially in light of tools that bitch when methods have "too many lines". Our shop standard calls for

```ruby
ruby_method(
  param1,
  param2,
  param3)
# other code follows
```

YMMV, but if I can get away without an explicit inline comment to disable RuboCop and/or Reek checks and enable them again, with more commentary explaining why the first are there, then I'm a much happier camper.

**Comment by tommydangerous** [comment]
I go for:
```ruby
ruby_method(
  1,
  2,
  3,
)
```

**Comment by jdickey** [comment]
@tommydangerous And that's because…?

**Comment by tommydangerous** [comment]
I personally feel it is visually easier to separate the arguments and the end of the method call.

**Comment by scudelletti** [comment]
When coding ruby I also close parenthesis in a new line as @dakull described. However @jdickey has a point.

A thing that I would consider is that other communities as Clojure usually don't close parenthesis in a new line and for sure we use a lot more parenthesis when coding Clojure. 

Maybe there is a good reason behind that style and we can learn from that. 
[Clojure Style Guide](https://github.com/bbatsov/clojure-style-guide)

I'm not sure about which one is better though. :dancer:

**Comment by dakull** [comment]
yeah, I have to say that @jdickey version is quite intriguing, I'll have to test with some real code and see how it _feels_

**Comment by davidsoncasey** [comment]
@jdickey I think that my preference for the closing parentheses on its own line is a habit from programming python, where I want to make it very clear what level of indentation a statement is at (and start the next line on that level). But your style is also quite readable, and I see the advantage of not using a line for a single character.

**Comment by jdickey** [comment]
@davidsoncasey I thought that might be the case for you (and likely @tommydangerous as well). Many of us who code in different languages have a tendency to carry around habits from one language into another; that very rarely approximates an unalloyed Good Thing.

**Comment by pirj** [comment]
This is pretty much covered in https://github.com/rubocop-hq/ruby-style-guide#method-arguments-alignment
