### ISSUE TITLE
Have guidelines for C extensions

### ISSUE THREAD

**Issue by v0dro** [rubocop-hq/ruby-style-guide#543]
Hi,

I'm from [SciRuby](https://github.com/sciruby), and we use a lot of C extensions in our gems. Currently we [specify these ourselves](https://github.com/SciRuby/nmatrix/blob/master/CONTRIBUTING.md#guidelines-for-interfacing-with-cc) as per our project needs

It would be great to have a formal specification which can be adhered to throughout the community.

**Comment by dakull** [comment]
@v0dro not so sure it's related to the style guide. Those look like best practices, useful link btw.

**Comment by v0dro** [comment]
Well C extensions are an integral part of many gems, and I think it's important that the C code is consistent with the Ruby code.

**Comment by dakull** [comment]
Maybe and adjacent style guide for writing C extensions in Ruby? this way one could go into details without issues.

**Comment by v0dro** [comment]
OR maybe we can have a section in this guide for C extensions? Having everything in one place looks like a better option.

**Comment by Ch4s3** [comment]
I think this would be useful. Maybe someone could browse a few gems that have extensions and see what makes sense.

**Comment by v0dro** [comment]
I can start that section with a few lines from what I've learned in my experience. But I'll need support from maintainers :P

**Comment by dakull** [comment]
I'm quite interested in idiomatic Ruby C extensions - I was already checking out gems and guides.

**Comment by v0dro** [comment]
Cool. PR coming soon :)

**Comment by v0dro** [comment]
I've started writing the guide in this document: https://github.com/v0dro/v0dro.github.io/blob/source/source/_posts/2018-08-15-rfc-ruby-c-extension-conventions.markdown

Also my apologies for the two year delay :D

**Comment by bbatsov** [comment]
No worries! Things always happen slow here! :D I think that C extensions are outside the scope of that guide (which is already quite long), but we can always refer to extra resources/additional guides from it.
