### ISSUE TITLE
The Safe Navigation Operator (&.)

### ISSUE THREAD

**Issue by maslenkov** [rubocop-hq/ruby-style-guide#553]
As I see in [source-code-layout](https://github.com/bbatsov/ruby-style-guide#source-code-layout) section operators should be separated by spaces. But the same feature in another languages does not separated. So I prefer syntax without spaces.

Should it be in this guide?

**Comment by bbatsov** [comment]
If it's causing any confusion - I guess we should add some rule here (in one form or another).

**Comment by kambata940** [comment]
IMO `foo&.bar&.baz` isn't very readable. @bbatsov what do you think about `foo &.bar`? Although it may be unclear in situations as `foo && bar && baz &.something &.other`, but some brackets will fix the thinks up.
```
foo && bar && (baz &.something &.other)
```

**Comment by jdickey** [comment]
I'd argue for a recommendation that it be used *without* surrounding spaces.

Rationale: You (almost) never see code like `baz . something . other`; we've seemed to agree over the last 40+ years that `baz.something.other` is clearer. Why, then, frown upon `baz&.something&.other`, when the latter is an extension of the semantics of the former?

**Comment by kambata940** [comment]
The thing is that `&` looks like a part of the previous word, that's why I suggest the variant *with* space before the operator and *without* space after it. Just it not readable enough.

Without space:
``` 
ends_with_f&.ends_with_l&.ends_with_j&.method
```

With space before:
```
ends_with_f &.ends_with_l &.ends_with_j &.method
```
Yes, it seems little strange, but at least is clear what going on.

**Comment by jdickey** [comment]
I think that either is "strange" because it's new to most of us, and it's just human nature to resist changing something we're already doing. Use of the safe-navigation operator itself is going to take some time to really become widespread for just that reason. I'd still prefer the "standard" notation, (`bar&.something&.other`) simply for its congruence with the original navigation operator it supplements.

The existing guide is littered with edge cases, such as [ranges](https://github.com/bbatsov/ruby-style-guide#no-space-inside-range-literals) where no spaces are to be introduced (use `1..3` rather than `1 .. 3`). There is no present discussion of the traditional navigation operator (`.`); perhaps because the existing in-the-wild convention is so uniformly used. why introduce yet another edge case?

@bbatsov and team, what do you guys think?

**Comment by eliotsykes** [comment]
This safe navigation operator conversation was started a year ago, and wondering if anyones developed any of their own rules of thumb for its use since then. Myself I'm still finding it a little clunky, but would love to find a way make it readable to these old eyes.

**Comment by jdickey** [comment]
Our internal standard explicitly calls for it to be treated identically to the unsafe navigation operator `.`, which ordinarily has no preceding or following whitespace.

**Comment by Justin-Maxwell** [comment]
In some future time, someone will invent a way for computers and the people who program them to be able to work with more than 95 symbols, and we'll be able to use characters like ↣ to navigate to a member attribute, and perhaps ↦ if the navigation should terminate cleanly when the navigation fails.  Please excuse my poor hand sketches.

(and if it needs saying: Yes, changes like these would probably need unicode support to be pushed down to keyboard hardware, and are a loooong way off, but these ideas need to be seeded, and if not where developers talk code style and readability, then where?)

**Comment by maslenkov** [comment]
@eliotsykes 
> This safe navigation operator conversation was started a year ago, and wondering if anyones developed any of their own rules of thumb for its use since then.

I've found for my self and our team.
As Robert Martin writes in his "Clean Code" book:

> Horizontal Openness and Density
> We use horizontal white space to associate things that are strongly related and disassociate
things that are more weakly related. 

These things(receiver and method) is not disassociated so we don't use spaces around `&.`. I can do PR.

BTW: `ends_with_f&.ends_with_l&.ends_with_j&.method` is a message chain which should be avoided.
