### ISSUE TITLE
Suggestion on the most readable format for rand()

### ISSUE THREAD

**Issue by DamirSvrtan** [rubocop-hq/ruby-style-guide#567]
I often times see people writing code for rand with an additional offset instead of using a range.

Let's say you want to simulate a roll of the dice, the most common piece of code you'll see is:

``` ruby
rand(6) + 1
```

`rand(6)` will return a number from zero to five and then you add 1 to get valid dice numbers.

However, a better approach would be to use a range:

``` ruby
rand(1..6)
```

It's really clear that you'll be able to get numbers from 1 to 6.

@bbatsov please tell me if you're fine with this, then I'll make a PR to incorporate it to the guide. Thnx!

**Comment by DamirSvrtan** [comment]
And If you're okay with me submitting this guide, where would be the appropriate place? Under the #numbers section?

**Comment by bbatsov** [comment]
What you're saying makes sense. Not sure if it's something common enough, so it should be covered by the style guide, but it definitely yields more readable code IMO.

**Comment by DamirSvrtan** [comment]
In my experience, you don't see it that often, but once you see it you'll see it in code multiple times. It really depends on the project.

I want to put this in Rubocop so first wanted to update the style guide so they're in sync.

**Comment by DamirSvrtan** [comment]
Also, why I'd want to put this in the Styleguide is because the more common used format (`rand(6) + 1`) is too much C-like instead of Ruby-like.

**Comment by DamirSvrtan** [comment]
@bbatsov are you cool with merging this in?

**Comment by cesc1989** [comment]
@DamirSvrtan IMO, you should go ahead and do the PR and let the maintainer take care of it.
