### ISSUE TITLE
Unless with Exception

### ISSUE THREAD

**Issue by courtneyburas** [rubocop-hq/ruby-style-guide#586]
Hey, I'm actually in a coding bootcamp which links us to this repo the first week to learn how ruby should look. We're supposed to fix a file and the file uses 'raise' with 'unless' which isn't mentioned at all in the style guide. Is this ok? Is it not ok? Obviously, I can't add because I don't know.

**Comment by TommyLike** [comment]
I think it's a good try,it's much more like a sentence to almost anyone than `raise !if`.
