### ISSUE TITLE
Style/DoubleNegation should be allowed for return values

### ISSUE THREAD

**Issue by donv** [rubocop-hq/ruby-style-guide#591]
Hi!

A typical pattern is to have a boolean query to read object state that is not stored as a boolean inside the object:

``` ruby
class MyClass
  def close
    @closed_at = Time.now
  end

  def closed?
    !!@closed_at
  end
end
```

The conversion to boolean is to encapsulate the inner state of the object.  The double negation is idiomatic for "convert to boolean".  I agree with the style guide that it should not be used in control flow, but I think it is good style when using outside control flow.

Rubocop 0.41.1 lists the above as an offence.  It should not since the double negation is not in a control flow.

**Comment by antstorm** [comment]
I'm definitely in favour of allowing double negation for casting values to boolean

**Comment by chilicheech** [comment]
Either that or create a default/Kernel `.to_b` or `.to_bool` method to do that. `.to_bool` would be clearer that `!!`.

**Comment by bbatsov** [comment]
While I understand your reasoning, I still don't see why can't we just do a `nil?` check and be more explicit about our intentions.

**Comment by antstorm** [comment]
@bbatsov Usually it's for targeting both `false` and `nil` at the same time

**Comment by bbatsov** [comment]
I understand this well enough, but this also means someone design a poor api if at some point you can have either `false` or `nil`...

**Comment by bbatsov** [comment]
> Either that or create a default/Kernel .to_b or .to_bool method to do that. .to_bool would be clearer than !!.

Someone should file a Ruby ticket for this.

**Comment by antstorm** [comment]
@bbatsov fair comment, but unfortunately in ruby world this is very common

**Comment by bbatsov** [comment]
> @bbatsov fair comment, but unfortunately in ruby world this is very common

It's common only because people are some used to this because of the extremely crappy built-in nil-happy APIs.

**Comment by antstorm** [comment]
@bbatsov yes, but we live in a non-idealistic world, otherwise we wouldn't need `rubocop` at all :)

**Comment by juanibiapina** [comment]
By looking at the number of upvotes versus number of people arguing against it, this seems another example where this style guide is not community driven.

**Comment by bf4** [comment]
I usually disable this cop for rspec matchers when I to cast anything truthy to true, e.g. in [vcr](https://github.com/vcr/vcr/blob/0ce29d08d492792ffecbec468e70a638e9e9f140/lib/vcr/test_frameworks/rspec.rb#L30)

```ruby
          when_tagged_with_vcr = { :vcr => lambda { |v| !!v } }

          config.before(:each, when_tagged_with_vcr) do |ex|
```

**Comment by tom-lord** [comment]
To echo the concerns raised above:

I agree that `!!foo` is *usually* redundant and can be replaced with `foo`. However, there are some legitimate use cases for doing this - such as when implementing the [null object pattern](http://www.virtuouscode.com/2011/05/30/null-objects-and-falsiness/).

Despite the [rubocop styleguide recomendation](http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/DoubleNegation), **the following are _NOT_ equivalent!!**:

```
# bad
!!something

# good
!something.nil?
```

If `something == false`, then `!!something == false` but `!something.nil? == true`.

Making this substitution blindly may break code.

I am not a fan of this cop in general; I don't consider the above refactoring to be an improvement. As mentioned above, an `Object#to_bool` method may be a little cleaner, but the `!!` pattern is still very legible, and a common pattern implemented in other languages.

However, I do recognise that using `!!` as a *non-return value* is a genuine code smell. Perhaps the ruby style guide should be updated to reflect this: One should *avoid* use of `!!` in general; and never use it as a non-return value?

**Comment by mikegee** [comment]
in #688, @bpieck raised a point that isn't already explicit here: 

> In my case I want to provide true or false to the outside - so to json output.

I agree. I think this is the valid case for `!!`. (Perhaps other output formats too. XML?)

Considering the rarity of these, I choose to disable the cop inline when it comes up.

**Comment by gkop** [comment]
>  The double negation is idiomatic for "convert to boolean"

Yes! Not just in return values but any time I want to coerce to boolean - this is the idiom in Ruby, right?

**Comment by mikegee** [comment]
@gkop this is highly debated, but I claim it is most idiomatic to not convert to boolean; leave the value "truthy" or "falsey", not explicitly `true` or `false`.

**Comment by gkop** [comment]
Ah thanks @mikegee . Specifically, in enumerating the acceptable cases for !!, in addition to the return value case given in the issue description, I think it's reasonable to use !! when calling a method that expects a boolean argument. I understand generally it's more Ruby-ish for a method to accept truthy/falsey, but in some cases it's reasonable to expect a boolean IMO, for example when the parameter is going to be inserted into a not-null boolean database column, the conversion has to take place _somewhere_ right?

**Comment by cutalion** [comment]
Another example where `!!` makes code shorter is in combination with `&.` operator.
Any alternatives to that?

```ruby
def banned?
  !!banned_until&.future?
end
```

I would agree if one would complain about lots of special chars in a single line, though.

**Comment by tom-lord** [comment]
@cutalion One could _argue_ that the `!!` is superfluous there; it doesn't matter if `banned?` returns `nil` instead of `false`.

It's a good example of using `!!` to ensure "boolean" consistency though, which may be useful e.g. if integrating with an API that does expect boolean values.

**Comment by cutalion** [comment]
It was without `!!` until today.

Today our frontend dev, who started to migrate code to typescript, asked me "Why `banned` field sometimes null? What does it mean? User does not have permissions to see the value or what?"

I decided to always return boolean to make API less surprising. 
Had do disable this cop for the project. 
Would be nice to have a configuration which sometimes allows `!!`.

**Comment by mikegee** [comment]
@cutalion that is exactly the case I support using `!!`, [as noted above](https://github.com/rubocop-hq/ruby-style-guide/issues/591#issuecomment-349655571). I would disable the cop inline with something like:

```ruby
def banned?
  !!banned_until&.future? # rubocop:disable Style/DoubleNegation
end
```

Even better would be if you have some kind of "serializer" object and you can delay the cast to boolean until you concoct the JSON:

```ruby
class MyObjectSerializer
  def to_json
    {
      ...
      banned: !!object.banned?
      ...
    }
  end
end
```
That way, you could exclude this whole file (or the directory full of serializers) from `Style/DoubleNegation`.

**Comment by bbatsov** [comment]
I think I've mentioned this elsewhere already. I'd happily take a PR which extends the existing rules and specifies some acceptable use-cases for `!!`. I'm also open to making the RuboCop check configurable.

**Comment by morgvanny** [comment]
I see a few PRs open, attempting to specify acceptable use cases. Are you asking for more of that, or rather a PR for the gem itself so that it allows for them?
