### ISSUE TITLE
On the position of attribute macros within class

### ISSUE THREAD

**Issue by fuadsaud** [rubocop-hq/ruby-style-guide#599]
Since they could be considered simple method definitions, my gut feeling tells me that attribute macros (like `attr_reader :name`) should be placed after the `initialize` method definition. Currently, the guideline advises putting them before the class level definitions, which I personally find to be a little unreasonable:
- it's the only an instance level definition that comes before the class level ones;
- when they are private or protected they are usually put right after the `private` and `protected` visibility definitions (at instance level)
- class level attribute macros should come before or after them?

I'd like to raise the discussion about that and know if there's any special reasoning to treat these method definitions differently. If that's not the case I'd propose to advise their definition to be put either before or after the `initialize` method definition in case they are public (personally I'd go with the latter) and right after visibility declarations otherwise.

**Comment by bbatsov** [comment]
I get your point, but the current recommendation follows a deeply rooted convention that you'll see pretty much everything. The guide vows to respect and promote established community practices.

There's also the fact that no one voiced their support for your suggestion for almost 3 years. :-)
