### ISSUE TITLE
No rule for naming private variables

### ISSUE THREAD

**Issue by adamgotterer** [rubocop-hq/ruby-style-guide#621]
Should there be any standard around `@_private_var` vs `@private_var`?

**Comment by jdickey** [comment]
Can anyone show that there's a predominance of `@_private_var` in the wild, or is it simply Java-esque RedundantDecorationSyndrome? I'd make the counter-argument that public attributes are a code smell; your public API should expose the result of queries (as distinct from [commands](https://martinfowler.com/bliki/CommandQuerySeparation.html)) *except* in the case where your public API consists entirely of a single `.call` method, which obviously returns the result of an action.

Externally-accessible state is a symptom, if not the richest source of, defects in your code; eliminating it requires a change in how you think about architecture but the rewards once in production far outweigh the adjustment effort.
