### ISSUE TITLE
Introduce a recommended style for float division

### ISSUE THREAD

**Issue by Drenmi** [rubocop-hq/ruby-style-guide#628]
By default, Ruby will perform integer division when both receiver and argument are integers. The way you perform float division on integers is to coerce one or more of them into a float. I propose there be a guideline for which part--receiver or argument--should take the `#to_f` coercion.

I am leaning towards both the receiver and the argument being coerced, because:

1. If you only coerce one, changing the code gets more risky, because you may unwittingly replace the float coerced one with an integer, regressing to integer division.

2. ~~Choosing one to apply `#to_f` to is (as far as I can see) completely arbitrary.~~

**Possible styles:**

```ruby
# both
a.to_f / b.to_f

# receiver
a.to_f / b

# argument
a / b.to_f
```

Another option could be to recommend `#fdiv`:

```ruby
a.fdiv(b)
```

WDYT?

**Comment by backus** [comment]
Personally I'd prefer the default style to **not** be a form that requires `#to_f` on both sides. Since it isn't necessary it is dead code to require both. 

Personally it seems like the preference should be to enforce that the left hand receives `#to_f`. They you always know you are dealing with `Float#to_f`. Not true if the right hand is the thing being coerced. Since it is ruby I still don't really know what `/` means for unknown type `a` :smile:

**Comment by Drenmi** [comment]
@backus: Unless `#to_f` was not overridden for type `a` (but let's not go there. 😅) I think your argument is sound, and you're well on your way to win me over. 😀

**Comment by GBH** [comment]
Got burned very recently on this bug/feature. Was wondering if there was a cop that would prevent this. It's very easy to make `5/2 == 2` when you really expected `2.5`. If you forget this gotcha you're in trouble.

**Comment by bbatsov** [comment]
@Drenmi Let's recommend left-hand `#to_f` or `fdiv`. I think both are find approaching, provided you stick to them consistently.

**Comment by morus** [comment]
```
a = '1.1'
b = '2.1'
d = a.to_f / b.to_f
```
Does a rule that forces me to choose between turning it off or having broken code really make sense?
Of course in my real world sample a and b are not literals but parsed from xml ...

**Comment by bbatsov** [comment]
Well, that's not really in the scope of the rule - it deals with coercion of integers to floats.

**Comment by morus** [comment]
But It applies to any coercion. The rule does not check that it deals with integers. Understandable given the lack of explicit typing but that does not change the consequences...

**Comment by bbatsov** [comment]
I think you're confusing the guidelines here with the RuboCop cop. The cop obviously can't know the type of the receiver and it might yield false positives, but that has little to do with what the guidelines are intended for. On a related note - when dealing with an external data it's better to use `Float` than `to_f` most of the time.
