### ISSUE TITLE
An error occurred while Style/RedundantReturn cop was inspecting ...

### ISSUE THREAD

**Issue by keith-roberts** [rubocop-hq/ruby-style-guide#638]
Hi all,

I'm getting this error when I run Rubocop with the Checkstyle formatter.

Scanning /var/lib/jenkins/workspace/zzz@script/test/unit/datetime_test.rb
An error occurred while Style/RedundantReturn cop was inspecting /var/lib/jenkins/workspace/zzz@script/test/unit/datetime_test.rb.
undefined method `type' for nil:NilClass
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/style/redundant_return.rb:79:in `check_branch'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/style/redundant_return.rb:109:in `check_if_node'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/style/redundant_return.rb:82:in `check_branch'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/style/redundant_return.rb:75:in `on_method_def'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/mixin/on_method_def.rb:9:in `on_def'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:41:in `block (2 levels) in on_def'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:96:in `with_cop_error_handling'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:40:in `block in on_def'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:39:in `each'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:39:in `on_def'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:45:in `on_begin'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/ast_node/traversal.rb:88:in `on_class'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:45:in `on_class'
(eval):2:in `block in on_begin'
(eval):2:in `each'
(eval):2:in `on_begin'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:45:in `on_begin'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/ast_node/traversal.rb:12:in `walk'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/commissioner.rb:58:in `investigate'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/team.rb:120:in `investigate'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/team.rb:108:in `offenses'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cop/team.rb:51:in `inspect_file'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:243:in `inspect_file'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:190:in `block in do_inspection_loop'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:222:in `block in iterate_until_no_changes'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:215:in `loop'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:215:in `iterate_until_no_changes'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:186:in `do_inspection_loop'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:101:in `block in file_offenses'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:111:in `file_offense_cache'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:99:in `file_offenses'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:90:in `process_file'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:68:in `block in each_inspected_file'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:65:in `each'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:65:in `reduce'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:65:in `each_inspected_file'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:57:in `inspect_files'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/runner.rb:36:in `run'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cli.rb:71:in `execute_runner'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/lib/rubocop/cli.rb:27:in `run'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/bin/rubocop:13:in `block in <top (required)>'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rubocop-0.44.0/bin/rubocop:12:in `<top (required)>'
/var/lib/jenkins/.rbenv/versions/2.3.0/bin/rubocop:23:in `load'
/var/lib/jenkins/.rbenv/versions/2.3.0/bin/rubocop:23:in `<top (required)>'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `load'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:74:in `kernel_load'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli/exec.rb:27:in `run'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:332:in `exec'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:20:in `dispatch'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/cli.rb:11:in `start'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:34:in `block in <top (required)>'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/var/lib/jenkins/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.13.7/exe/bundle:26:in `<top (required)>'
/var/lib/jenkins/.rbenv/versions/2.3.0/bin/bundle:23:in `load'
/var/lib/jenkins/.rbenv/versions/2.3.0/bin/bundle:23:in `<main>'
...
10 errors occurred:
An error occurred while Style/RedundantReturn cop was inspecting /var/lib/jenkins/workspace/zzz@script/test/unit/datetime_test.rb.
An error occurred while Style/RedundantReturn cop was inspecting /var/lib/jenkins/workspace/zzz@script/app/helpers/application_helper.rb.
... + 8 more errors the same

Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
Mention the following information in the issue report:
0.44.0 (using Parser 2.3.1.4, running on ruby 2.3.0 x86_64-linux)
Finished in 477.8753655059263 seconds

**Comment by bbatsov** [comment]
Such problems should be reported on RuboCop's issue tracker.
