### ISSUE TITLE
Pros and cons of aligning assignment or hash values

### ISSUE THREAD

**Issue by gnapse** [rubocop-hq/ruby-style-guide#642]
I was wondering if this style guide had anything to say about the pros and cons of these two alternative styles:

```ruby
# align assigned values
hello     = "world"
goodbye   = "everyone"
greetings = "to you"

# don't align assigned values
hello = "world"
goodbye = "everyone"
greetings = "to you"
```

The same alternatives can be applied to hash values in multi-line hash literals:

```ruby
# align assigned values
hash = {
  hello:     "world",
  goodbye:   "everyone",
  greetings: "to you"
}

# don't align assigned values
hash = {
  hello: "world",
  goodbye: "everyone",
  greetings: "to you"
}
```

Or virtually everywhere in which a set of consecutive lines share a similar structure, but different lengths of its parts. A regular `Guardfile`, for instance, aligns the blocks to all start in the same column:

```ruby
# blocks aligned
watch(%r{^app/(.+)\.rb$})                           { |m| "spec/#{m[1]}_spec.rb" }
watch(%r{^app/(.*)(\.erb|\.haml)$})                 { |m| "spec/#{m[1]}#{m[2]}_spec.rb" }
watch(%r{^app/controllers/(.+)_(controller)\.rb$})  { |m| ["spec/routing/#{m[1]}_routing_spec.rb", "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb", "spec/acceptance/#{m[1]}_spec.rb"] }
watch(%r{^spec/support/(.+)\.rb$})                  { "spec" }
watch('config/routes.rb')                           { "spec/routing" }
watch('app/controllers/application_controller.rb')  { "spec/controllers" }

# blocks not aligned
watch(%r{^app/(.+)\.rb$}) { |m| "spec/#{m[1]}_spec.rb" }
watch(%r{^app/(.*)(\.erb|\.haml)$}) { |m| "spec/#{m[1]}#{m[2]}_spec.rb" }
watch(%r{^app/controllers/(.+)_(controller)\.rb$}) { |m| ["spec/routing/#{m[1]}_routing_spec.rb", "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb", "spec/acceptance/#{m[1]}_spec.rb"] }
watch(%r{^spec/support/(.+)\.rb$}) { "spec" }
watch('config/routes.rb') { "spec/routing" }
watch('app/controllers/application_controller.rb') { "spec/controllers" }
```

An argument could be made that aligning improves readability, but conversely, it would create the need to change adjacent lines when the longest line in the set changes and breaks the alignment. Any thoughts?

**Comment by charger** [comment]
IMHO readability of the aligned version is a fewer problem than needs to adjacent after changing code.

**Comment by jdickey** [comment]
@charger I'd disagree, if only because it's so easy to automate. Most plugin-capable editors appear to have suitable plugins/macros, and adding automation support to tools like RuboCop should be very straightforward. Which is done more often, modifying code that needs to be formatted, or reading code that's more easily read and understood when well-formatted?

**Comment by rosshambrick** [comment]
I don't feel strongly either way, but my argument against the alignment would be that adding one additional line creates a diff for the entire block because all lines need to be realigned.

This is how `go fmt` works and it's mildly annoying.

**Comment by jdickey** [comment]
@rosshambrick I see; yeah, that makes sense. No matter which way you go or what tooling you employ, somebody's going to have to do extra work sometime that's going to tick them off, either reading diffs or reading the code itself.

I've experimented with a convention where I indent values based on the longest indentation in the initial setup, so you might initially have

```ruby
hello     = "world"
goodbye   = "everyone"
greetings = "to you"
```

When you add something that's longer than the existing indentation, you use *that* length for anything that gets added later:

```ruby
hello     = "world"
goodbye   = "everyone"
greetings = "to you"

abercrombie = "fitch"
goldman     = "sachs"
```

making it blindingly obvious to the casual reader *hey, this was added later.*  That had mixed reviews from the team: some thought it was a great idea; others hated it passionately. Each new project chooses whether to use the convention or not; once that decision is taken, it stays.

I'm amenable to whatever decision is taken here.

**Comment by bbatsov** [comment]
I think we should avoid recommending (or discouraging) alignment in the style guide, as there are both many people who like and dislike it. In the absence of a clear consensus it's best to leave it up to developers to figure things out.

**Comment by bbatsov** [comment]
(At the very best we can just have a mild encouragement of alignment)

**Comment by kigster** [comment]
I want to voice a strong opinion for alignment — and based on user research studies I can try to dig up and quote later, humans are better at quickly perceiving tabular information. I also believe that it turns out that there is a group of people which can infer the meaning equally quickly from both formats, but the majority of us reads tabulated data much much faster.

The "git diff" argument is a moot point, because you can exclude white space from the diff, by passing `-bw` to `git` or by using the UI feature on Github:

![diff-settihgs](https://user-images.githubusercontent.com/259982/61983319-c6745e80-afb4-11e9-8350-af26df84a12c.png)
