### ISSUE TITLE
Descussion: calling of functional objects

### ISSUE THREAD

**Issue by jomei** [rubocop-hq/ruby-style-guide#648]
I have a functional object like a 
```ruby
class Foo
  def call
     # some code here
  end
end

foo = Foo.new
```

How should I call it?
`foo.call`  or `foo.()`

**Comment by jdickey** [comment]
The Guide [says](https://github.com/bbatsov/ruby-style-guide#proc-call) that you should

> Prefer `proc.call()` over `proc[]` or `proc.()` for both lambdas and props.

So, by the book, you want `foo.call()`.

*However,* this is one of a very select number of rules that we internally are getting around to agreeing should have an exception *precisely for* well-named service (functional) objects. Consider:

```ruby

class PostToQuora
  def self.call(credentials, item)
    new(credentials, item).call
  end

  def call
    # do stuff
  end

  protected

  def initialise(credentials, post)
    # ...
  end

  # ...
end
```

Now, to get RuboCop (per the Guide) not to yell at you, you'd invoke that by calling

```ruby
  PostToQuora.call(user_credentials, current_post)
```

We would argue that it reads more naturally to the maintainer and reviewer as

```ruby
  PostToQuora.(user_credentials, current_post)
```

The use of the `#call` *instance* method inside the `.call` *class* method remains unchanged. (Use of `#call` in *literal* procs and lambdas remains unaffected and consistent with the existing rule.) But the current rule as worded, and as implemented by RuboCop and any other tool that takes the current wording literally and unconditionally, isn't always the best use of the language. Again, in our opinion.

**Comment by bbatsov** [comment]
I've always been on the fence about this. I guess your reasoning, but I think that for newcomers its extremely weird to see a method call without a method name. The wording of the rule can certainly be improved, though.
