### ISSUE TITLE
Space following left parens( mode: bunfight)

### ISSUE THREAD

**Issue by Justin-Maxwell** [rubocop-hq/ruby-style-guide#663]
So I don't even know where to begin with this one, and this is going to be the wrong place...  But I want to seed the thought and see if I am alone in the world...

I've felt for a long time that including a space after the opening parenthesis in an argument list makes a really significant readability improvement, and it's something I've done consistently as a result during those periods of my life I've had my head in code over the years.  The appearance of Ruby's keyword arguments has only made the case that much stronger.

```thing = object.method( debate: parameter, option: :feijoa).eat_me```
vs
```thing = object.method(debate: parameter, option: :feijoa).eat_me```

It may not seem like much, but to my eye and mind, the first one scans much faster than the second.

```thing = object.method( debate: parameter, option: :feijoa ).eat_me``` seems worse though

So:  
* Is it just me? 
* **Where should a discussion on something like this happen?** 
* Has anyone seen a Ruby linter that allows a rule to be set to mandate a space after the opening-parens only of a method call/parameter list?  

[also, while I'm at it: 
It'd be better if there was never a space before an = when used as assignment, it should be ```thing=```, which would mean less confusion when switching from languages using = for equality comparison.  AFAICT it doesn't seem to cause any problems, and is consistent with Ruby setter conventions... 
And, since I'm on a roll, can we please all have unicode keyboards and code parsers so we can type ≠ when we mean ≠ (etc) some time this century?  I'll get my coat…]

**Comment by bbatsov** [comment]
> Is it just me?

Seems so. No one else opted to participate in this conversation.

> Where should a discussion on something like this happen?

That's the right place.

> Has anyone seen a Ruby linter that allows a rule to be set to mandate a space after the opening-parens only of a method call/parameter list?

I haven't seen one.
