### ISSUE TITLE
Lint/RescueWithoutErrorClass falsy in 0.50

### ISSUE THREAD

**Issue by morgoth** [rubocop-hq/ruby-style-guide#674]
The new `Lint/RescueWithoutErrorClass` raises on valid syntax according to https://github.com/bbatsov/ruby-style-guide#no-blind-rescues:
```
def my_method
  2 + 2
rescue => e
  puts e
end
```

**Comment by donv** [comment]
The example above is listed as "good" in the style guide.  Will rubocop be modified to accept it?

**Comment by bbatsov** [comment]
@donv I guess this should be made configurable. That's an oversight on our part. @morgoth This should be a ticket in RuboCop.

**Comment by Drenmi** [comment]
Continued in [RuboCop#4851](https://github.com/bbatsov/rubocop/issues/4851).

**Comment by andy-smith-msm** [comment]
I really value Rubocop as a tool and it's helping here with my effort to bring clarity to our codebase, however, as part of that clarity we assume that it implements the defaults to be exactly as per the Ruby Style Guidelines and in that respect before this change it wasn't incompatible with the style guidelines.

We go as far here as saying _no_ settings are overridden by a configuration file. If you have a legitimate  reason for using a non default approach then you put an inline comment with your reason and if you decide later that there is a better approach and one that can meet the requirement you simply remove that override. This allows one to get continuous improvement and a continuous feed from upstream from the style guide and the day that you put override files in to the project you lose a lot of that benefit from trusting the tool.

I think this perspective isn't unique and we find it strange that a change in an area that is so obvious for Rubyists has been assumed to be helpful.
