### ISSUE TITLE
Brackets and curly braces

### ISSUE THREAD

**Issue by MrBerg** [rubocop-hq/ruby-style-guide#681]
The style guide is unclear on what to do when brackets and curly braces touch. https://github.com/bbatsov/ruby-style-guide#spaces-braces
For example, space or no space between the left bracket and left curly brace in this method call here: 
`method_call({foo: "bar", baz: "quux"}, 1)`? Does it depend on whether there are spaces inside the hash literal?
What about this array of hash literals? 
`[ { foo: "bar" } , { a: 1 } ]`
Should there also be a space between (right) curly braces and commas (as above) or periods (as below), in addition to the square brackets?
`foo.partition { |value| value.even? } .each { |array| puts array.to_s }`

My aesthetic preference would be to answer no to all of these.

**Comment by bbatsov** [comment]
> For example, space or no space between the left bracket and left curly brace in this method call here:
method_call({foo: "bar", baz: "quux"}, 1)? Does it depend on whether there are spaces inside the hash literal?

No spaces and no.

> What about this array of hash literals?
[ { foo: "bar" } , { a: 1 } ]

No.

> Should there also be a space between (right) curly braces and commas (as above) or periods (as below), in addition to the square brackets?

No and no.

> My aesthetic preference would be to answer no to all of these.

You got it all right. :-)
