### ISSUE TITLE
`&&=` is not reliable (maybe only for some versions)

### ISSUE THREAD

**Issue by EdmundLeex** [rubocop-hq/ruby-style-guide#691]
In 2.3.3

```ruby
[1] pry(main)> a &&= nil.a
=> nil
[2] pry(main)> a &&= 1.to_s
=> nil
[3] pry(main)> a = 1 && 1.to_s
=> "1"
[4] pry(main)> a &&= 1.to_s
=> "1"
[5] pry(main)> a &&= nil.a
NoMethodError: undefined method `a' for nil:NilClass
from (pry):5:in `__pry__'
```

Because of this, I wouldn't recommend using it.

**Comment by EdmundLeex** [comment]
I have started an SO thread to discuss that. And I came to the conclusion of "don't use `&&=`".

**Comment by pochmann** [comment]
Does exactly what I expected it to. I don't see any unreliability.

**Comment by pirj** [comment]
Sorry, I don't really understand the lack of reliability in the application of `&&=`. It seems pretty consistent with what it does.
```ruby
x &&= y
```
is basically a shorthand for:
```ruby
x = y if x
```
