### ISSUE TITLE
positive? vs > 0

### ISSUE THREAD

**Issue by Ana06** [rubocop-hq/ruby-style-guide#701]
I think we need to add to the Ruby Style guide what is preferred, [`positive?`](https://ruby-doc.org/core-2.5.0/Numeric.html#method-i-positive-3F) vs `>0`

I personally do not see a reason to use this `positive?` method, as `> 0` was already clear, but maybe someone come up with a reason to use it.

**Comment by bbatsov** [comment]
I guess it depends on whether you favour the numeric predicates in general or no. Probably there should be just some generic rule saying that you should either stick to comparison operators or to predicate methods.

**Comment by marcandre** [comment]
My feeling is that `nil?`, `zero?`, `positive?` are useful for `Symbol#to_proc`:

```ruby
def validate(numbers)
  numbers.none(&:nil?).all?(&:positive?)
end
```

The guide states that numeric comparisons are ok, so no preference

FWIW, I don't understand the community's love for `nil?` 😸

**Comment by bbatsov** [comment]
> My feeling is that nil?, zero?, positive? are useful for Symbol#to_proc:

Good point. 

> FWIW, I don't understand the community's love for nil? 😸

Same here. :-)

**Comment by pirj** [comment]
> I don't understand the community's love for `nil?`

Indeed! Even more so in the Rails world with their `current_user.blank?` checks.

**Comment by pirj** [comment]
Closing as stale.
