### ISSUE TITLE
The super method, parentheses with arguments?

### ISSUE THREAD

**Issue by jbhandari** [rubocop-hq/ruby-style-guide#703]
For the `super` method being a keyword in ruby, I am curious as to if it requires parentheses around arguments or not. I am having trouble grasping if it is declarative or not.

From my understanding these are correct:

```
def something_1
  super
end

def something_2
  super(:foo, :bar, :baz)
end

def something_3
  super :foo, :bar, :baz
end
```
 In terms of `something_2` vs `something_3` is one better over the other?

**Comment by mikegee** [comment]
Good question. I think you should choose between 2 and 3 based on whether you would use parens with typical method calls.

Keep in mind that `super` and `super()` are different things, in case that's unclear.

**Comment by jbhandari** [comment]
Well if that is the justification between 2 and 3, then wouldn't [the method parens](https://github.com/bbatsov/ruby-style-guide#method-parens) section put the debate between 2 to 3 to rest? In this case choose 2 over 3.  @bbatsov any input?

**Comment by bbatsov** [comment]
Good question, indeed!

I think @mikegee made the right suggestion, and given the fact that the guide suggests the use of parens with method calls I guess we should extend this to `super` as well.
