### ISSUE TITLE
brackets at arguments of a method is_a

### ISSUE THREAD

**Issue by izeal** [rubocop-hq/ruby-style-guide#708]
It is necessary to put brackets at arguments of a method `is_a`
In some examples they stand, and in some there is no

**Comment by mikegee** [comment]
Would you please provide examples to help clarify the issue?

**Comment by iLostTeacher** [comment]
This is the parts from different examples, you can find them using Ctrl+F
```
# good
something.is_a?(Array)
```

I think in the next examples also need parentheses for the arguments

```
# bad
paths = [paths] unless paths.is_a? Array
```

```
# bad
timestamp.is_a? Fixnum
timestamp.is_a? Bignum

# good
timestamp.is_a? Integer
```

**Comment by bbatsov** [comment]
Just an oversight. I've updated the examples to be consistent.
