### ISSUE TITLE
Are MiniTest-related style guidelines in scope?

### ISSUE THREAD

**Issue by gareth** [rubocop-hq/ruby-style-guide#709]
This is a question about whether test-library-specific guidelines are in scope for `ruby-style-guide`.

Specifically, I think it's important that bare MiniTest [`assert`](http://ruby-doc.org/stdlib-2.0.0/libdoc/minitest/rdoc/MiniTest/Assertions.html#method-i-assert) calls are always passed a `msg` parameter, to avoid the super-unhelpful generic failure message:

> Expected false to be truthy

Question: since this guideline is library-specific, does it fit in `ruby-style-guide`? Does it make a difference that it's a `stdlib` library?

The end goal is to submit a PR for Rubocop with a cop addressing this, but it would need to be in Style Guide for that to be relevant.

**Comment by bbatsov** [comment]
MiniTest guidelines are not in scope. I'd rather have them in a separate guide like https://rspec.rubystyle.guide/ (https://github.com/rubocop-hq/rspec-style-guide).

**Comment by bbatsov** [comment]
> The end goal is to submit a PR for Rubocop with a cop addressing this, but it would need to be in Style Guide for that to be relevant.

I do hope that we'll have a `rubocop-minitest` gem one of those days, but so far no one has opted to tackle it.

**Comment by bbatsov** [comment]
See https://github.com/rubocop-hq/minitest-style-guide and https://github.com/rubocop-hq/rubocop-minitest.
