### ISSUE TITLE
Misleading variable in the rule example about Perl-style variables 

### ISSUE THREAD

**Issue by dsbonev** [rubocop-hq/ruby-style-guide#714]
The `$LOAD_PATH` variable is available without requiring the `English` module, yet the following example leads the reader to believe otherwise. Please check the [documentation for the variables](http://ruby-doc.org/stdlib-2.4.0/libdoc/English/rdoc/English.html) that the module introduces and replace the variable in the example with a suitable one, e.g. `$$` and `$PROCESS_ID`.
```
# bad
$:.unshift File.dirname(__FILE__)

# good
require 'English'
$LOAD_PATH.unshift File.dirname(__FILE__)
```

**Comment by bbatsov** [comment]
I completely agree. We have to fix this and provide a better example.
