### ISSUE TITLE
Using safe navigation operator in assignement

### ISSUE THREAD

**Issue by dbesserman** [rubocop-hq/ruby-style-guide#723]
In the style guide, it's written that it's `ok` to use a `if` in an assignment.  

```ruby
something = something_else.downcase if something_else
```

Is it ok to use a safe navigation operator instead ?

```
# better ? 
something = something_else&.downcase
```

**Comment by mikegee** [comment]
These aren't quite the same. They are different when `something` already has a non-nil value.

The safe navigation version assigns `nil` to `something` when `something_else` is `nil`, but the `if` version avoids assigning to `something` when `something_else` is falsey.

**Comment by bbatsov** [comment]
Indeed. Generally whether it's ok or not depends on your particular usecase.
