### ISSUE TITLE
rubocop.readthedocs.io has bad code for `Style/ClassVars`

### ISSUE THREAD

**Issue by rwdj** [rubocop-hq/ruby-style-guide#733]
There's an issue with the documentation for [`Style/ClassVars`](https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassvars). The [explaination](https://github.com/rubocop-hq/ruby-style-guide#no-class-vars) for `Style/ClassVars` is clear, but the resolution on rubocop.readthedocs.io is unclear, and the provided code doesn't work.

Executing the [provided code](https://rubocop.readthedocs.io/en/latest/cops_style/#styleclassvars) in `irb 0.9.6` with `Ruby 2.5.1` gives:

    class A
      @test = 10
    end
    #=> 10
    class A
      def test
        @@test # you can access class variable without offense
      end
    end
    #=> :test
    A.new.test
    Traceback (most recent call last):
            3: from /Users/Ricky/.rbenv/versions/2.5.1/bin/irb:11:in `<main>'
            2: from (irb):12
            1: from (irb):9:in `test'
    NameError (uninitialized class variable @@test in A)
    Did you mean?  @test

So, no. We obviously cannot access class variable without offense. irb was _very_ offended.

**Comment by rwdj** [comment]
See [here](https://stackoverflow.com/questions/53984143/how-to-correct-style-classvars-in-rubocop/53984206#53984206) for more info.

**Comment by mikegee** [comment]
Code unrelated to the offense (the parts that would make it run without error) are not shown to eliminate distractions from what would and would not be an offense in Rubocop. The docs are just trying to say that the offense is on assignment, they don't fully demonstrate rewriting code to avoid class variables.

(This issue would get more attention in the Rubocop repository.)
