### ISSUE TITLE
Restore references to original discussions and sources

### ISSUE THREAD

**Issue by pirj** [rubocop-hq/ruby-style-guide#749]
After conversion to AsciiDoc (#748) due to significant markup changes, the references to original discussions and sources were lost.
A good place to check them [is the result of `git blame`](https://github.com/rubocop-hq/ruby-style-guide/blame/fc7b7e006f99a3d1025f08efd3e80c1be9c2b62d/README.md).

Since this is a living document, it's very hard to rely on `git blame` in the long run to keep track of the sources, most of this information became harder to access after #729 already.

Having reference links to discussions in some way would be very helpful for the curious about the reasoning behind the recommendations.

**Comment by tejasbubane** [comment]
Assuming `discussions == github issues`, few ideas I can think of:

1. Give issue numbers with links for each rule in the style-guide itself - so readers can check out the reasoning.
2. Maintain a `DISCUSSIONS.md` file in the repo which lists issue numbers for each rule.
3. Create a github label for each rule and tag issues. Use these labels to seach/filter.

**Comment by pirj** [comment]
This is something that is really hard to do, and as far as I can tell, nobody volunteered for such an effort.

If a certain guideline is so unclear that even the guide maintainers can't explain the reasoning behind it, we should remove or significantly adjust such a guideline.

In `blame` we trust.
