### ISSUE TITLE
Trailing Comma in Multi-Line Hashes & Arrays?

### ISSUE THREAD

**Issue by benhamill** [rubocop-hq/ruby-style-guide#76]
I think I first ran into this style in Python, but I can't be sure. The idea is that in a multi-line liter Hash or Array, you leave a trailing comma on the final element, thus:

``` ruby
DEFAULTS = {
  page: 1,
  per_page: 50,
  sort_by: name,
}
```

The thinking is that it makes adding elements easier; it's easy to forget to add a trailing comma to the line before your new element, you don't clutter a diff by changing a line that, really, didn't have to do with your changes and you can copy/paste any line up or down the list without having to edit it.

Personally, I like this style, but I know others disagree. I thought I'd see what people thought here. So... thoughts?

**Comment by jtara** [comment]
FWIW, recent versions of Javascript accept this, as well.

While I like the neatness of leaving the trailing comma off, it's bit me more times than I can think (when re-ordering items), and really should train myself into always adding the trailing comma.

Here's a use case that might be non-obvious, though really doesn't apply to a style-guide: generated code:

I treat all my Ruby files (and all other text files, for that matter...) as {{mustache}} templates in a pre-build step, so that product configuration can be incorporated from some YML configuration files. (Typically configuring multiple products from the same codebase.)

So, I sometimes do something like this:

``` ruby
    SOFT_ERRORS = [ {{#api.soft_errors}} '{{.}}', {{/api.soft_errors}} ]
```

This gives me e.g.

``` ruby
    SOFT_ERRORS = [  '12345',  '54321',  '22222',  ]
```

**Comment by bk322** [comment]
This is surprising that ruby doesn't allow things like
```ruby
DEFAULTS = {
  page: 1
, per_page: 50
, sort_by: name
}
```
given it focus on syntax sugar. I wonder if there is a special reason for that.

**Comment by Crenshinibon** [comment]
I recently did a lot of CoffeeScript and wondered why this isn't working:

```
DEFAULTS = {
  page: 1
  per_page: 50
  sort_by: name
}
```

**Comment by varcharlez** [comment]
Wow, surprised that people are actually against this. Having a trailing comma is good practice as 1) it saves errors when future maintainers add an item to the hash, and 2) it preserves diffs so that when new items are added, they are the only thing that comes up in the diff.

**Comment by franzliedke** [comment]
Indeed, this is very common in some other languages I know.

The main argument against it seems to be "code is read more often than it is changed". I'd actually argue that this might not be the case for hashes - I usually glance over them. :)

**Comment by brandondrew** [comment]
The arguments ***against*** this seems to boil down to this

> I'm *not accustomed to trailing commas* so it will confuse me or require extra thought on my part if they are allowed.

which is purely a matter of taste.

The arguments ***for*** it, on the other hand hold true for all people.  Shouldn't we give more weight to substantive benefits?

**Comment by joshuapinter** [comment]
> @benhamill The trailing comma always makes me think that there is something else after it, that someone might have omitted. The diff clutter is a valid argument, but not strong enough. I think that we should optimize our source code for human parsing (reading) and not for the `diff` utility.

Man, you got shit on pretty hard for disliking this style. Just wanted to say I'm in your camp. I've always disliked these trailing commas and go so far as disallow it in ESLint for our React and React Native platforms: https://eslint.org/docs/rules/no-comma-dangle#no-comma-dangle-disallow-trailing-commas-in-object-and-array-literals

Stay strong!

![fists up black panther](https://user-images.githubusercontent.com/180819/50853580-cfb31c00-133f-11e9-8f38-d62b40a78bb3.gif)
