### ISSUE TITLE
web site does not link to the repository at all

### ISSUE THREAD

**Issue by steveklabnik** [rubocop-hq/ruby-style-guide#761]
I had to look in the source to figure it out. The section about github should probably link to the repo!

**Comment by bbatsov** [comment]
Yeah, totally! Thanks for bringing this up!

I'm just wondering if it should only under "Contributing" or maybe somewhere in the into as well.

**Comment by bbatsov** [comment]
This was addressed by #760. I'll make the relationship between the site and the repo more prominent at some point.
