### ISSUE TITLE
If-else vs case

### ISSUE THREAD

**Issue by tejasbubane** [rubocop-hq/ruby-style-guide#764]
This came up in a PR discussion: https://github.com/rubocop-hq/rubocop/pull/7153#discussion_r295276529

Suggestion is to prefer `case` over `if-elsif-...-else`

```ruby
# bad
if arg == :foo
  foo_action
elsif arg == :bar
  bar_action
elsif arg == :baz
  baz_action
else
  final_action
end

# good
case arg
when :foo
  foo_action
when :bar
  bar_action
when :baz
  baz_action
else
  final_action
end
```

**Comment by bbatsov** [comment]
I thought we had this already. After all it's one of the primary usecases of `case`, so it makes sense to recommend it.
