### ISSUE TITLE
LeadingDot in MultiLine Chains with Pry, get confused with executing system command

### ISSUE THREAD

**Issue by AhmedKamal20** [rubocop-hq/ruby-style-guide#768]
When you use [pry](https://github.com/pry/pry) as your ruby console 
there is a conflict well happen with one of the rules here

Specifically, this [feature](https://github.com/pry/pry#command-shell-integration)
It will prevent one from using this [rule](https://rubystyle.guide/#leading-dot-in-multi-line-chains)

It will happen when you copy a code from your code base to execute in tour console

Example:
```ruby
ReportsMailer.with(user: user, report: report)
                   .report_generated
                   .deliver_now
```
Error:
```
[1] pry(main)*   ReportsMailer.with(user: user, report: report)  
[1] pry(main)*   .report_generated               
Error: there was a problem executing system command: report_generated
[1] pry(main)*   .deliver_now               
Error: there was a problem executing system command: deliver_now

```

**Comment by pirj** [comment]
This [`pry#1524`](https://github.com/pry/pry/issues/1524#issuecomment-324455658) may help in some way.

Related to #176.
