### ISSUE TITLE
what do you think of a general-coding-language-style-guide?

### ISSUE THREAD

**Issue by zzz6519003** [rubocop-hq/ruby-style-guide#769]

**Comment by bbatsov** [comment]
We've got something like this in the works. See https://github.com/pirj/meta-style-guide, which @pirj started recently. Generally I want to finish the updates to the core layout of the existing guides before codifying everything in the meta style guide.

**Comment by pirj** [comment]
Switched https://github.com/pirj/meta-style-guide to public.

**Comment by pirj** [comment]
Feel free to re-open. Please provide more details on what you have in mind.
