### ISSUE TITLE
Enforcing Empty Lines Around Class Structures

### ISSUE THREAD

**Issue by allentsai** [rubocop-hq/ruby-style-guide#772]
This probably isn't an issue, but I've been utterly unable to accomplish this. From: https://github.com/rubocop-hq/ruby-style-guide#consistent-classes - you see the order we should generally structure our classes.  The thing I am trying to enforce is the use of empty lines around each grouping.  I feel like I can't be the only person who wants this, but have been completely unable to locate the correct cop, and my google-fu has been too weak to find a solution.  Could someone please point me in the right direction?

Thank you!

**Comment by bbatsov** [comment]
That's a question for RuboCop's issue tracker.
