### ISSUE TITLE
Introduce a reference .editorconfig file

### ISSUE THREAD

**Issue by marcoXbresciani** [rubocop-hq/ruby-style-guide#774]
Why not (also) having a reference .editorconfig file added to the guide, for main rules? With such file, the IDEs may help the user enforcing the rules. Something like:

```
root = true
charset = utf-8
end_of_line = lf
indent_style = space
insert_final_newline = true
max_line_length = 72
tab_width = 8
trim_trailing_whitespace = true

[*.rb]
indent_size = 2

[*.md]
# Four spaces are defined as the unit of indentation.
indent_size = 4

[*.json]
indent_size = 4
```

or similar. See https://editorconfig.org/

**Comment by bbatsov** [comment]
Something like this is fine by me, although I'm not sure we'd be able to link to it from the generated site.

**Comment by marcoXbresciani** [comment]
As soon as possible I'll work on it and send a push request.

**Comment by pirj** [comment]
Closing along with #776. See the PR for the reasoning.
