### ISSUE TITLE
Idea - scientific notation ?

### ISSUE THREAD

**Issue by tdeo** [rubocop-hq/ruby-style-guide#803]
I've been using numbers in scientific notation in ruby and I realized they can be quite error prone, when seeing `10e5`, people may think it's `10**5` when it's actually `10**6`. There's no mention of scientific notation in the style guide, and I think it could be standardize (I'm willing to implement a cop for it).

From my experience in maths and physics, the usual rule for scientific notation is that the prefix should be between 1 (inclusive) and 10 (exclusive).

I think a good starting point would at least be :
- avoid leading zeroes after the decimal point (i.e. `0.01e6` would be more readable as `0.1e5`, or even `1e4`
- avoid trailing zeroes: `10e2` is less readable than `1e3`.

I understand there could be exceptions such as:
- prefer multiples of 3 after the exponent as `12.3e6` is easier to read as "12.3 millions" than `1.23e7`

Let me know what you think

**Comment by bbatsov** [comment]
Sounds good to me. PR welcome!
