### ISSUE TITLE
Prefer `include?` over `member?`?

### ISSUE THREAD

**Issue by dmolesUC** [rubocop-hq/ruby-style-guide#804]
In the spirit of

> Prefer `map` over `collect`, `find` over `detect`, `select` over `find_all`, `reduce` over `inject` and `size` over `length`.

it would be nice to specify (and have a cop to enforce) these. 

(And there might be other `Enumerable` synonym methods I'm not thinking of; I only noticed these because I ran across an old codebase that uses `member?`.)

**Comment by bbatsov** [comment]
That sounds reasonable to me. PR welcome. :-)

**Comment by dmolesUC** [comment]
Done. I have a [RuboCop fork](https://github.com/dmolesUC/rubocop) with the corresponding cop updates; should I file an issue there first or just file a pull request?

**Comment by bbatsov** [comment]
Just file a PR.

**Comment by dmolesUC** [comment]
Done: [rubocop#7793](https://github.com/rubocop-hq/rubocop/pull/7793). Thanks!

**Comment by koic** [comment]
This issue has been resolved by #805.
