### ISSUE TITLE
Empty line before each control structure

### ISSUE THREAD

**Issue by volontarian** [rubocop-hq/ruby-style-guide#82]
Regarding breaking up a method into logical paragraphs how about an empty line before control structures like if, while, return / return values, break, maybe also the ternary operator, etc. UNLESS it's the first line at the current "block".

Code sample:

``` ruby
def enforce_ssl?(req)
  enforce = false
  keys_by_type = { 
    :hosts => [:only_hosts, :except_hosts], :path => [:only, :except], 
    :methods => [:only_methods, :except_methods] 
  }

  if !keys_by_type.values.flatten.compact.any? { |option| @options[option] }
    return true
  end

  keys_by_type.keys.each do |type|
    enforce = enforce_ssl_for?(keys_by_type[type], req)

    next unless enforce

    keys_by_type.each do |other_type,sub_keys|
      next if type == other_type || !sub_keys.any? { |option| @options[option] }

      enforce = enforce_ssl_for?(sub_keys, req)

      break unless enforce
    end

    break if enforce
  end

  enforce   
end
```

**Comment by mikecmpbll** [comment]
this is the single biggest problem with code style consistency across our codebases and we don't have the power to do anything about it with rubocop atm. i know this is closed but it's a huge +1 from me :).

**Comment by pirj** [comment]
@mikecmpbll I suggest you contribute a cop to RuboCop that would take care of this.
There doesn't seem to be enough feedback to add this as a guideline to the style guide yet.
