### ISSUE TITLE
Odd formatting

### ISSUE THREAD

**Issue by MSP-Greg** [rubocop-hq/ruby-style-guide#829]
Using a variant of YARD to parse the README.adoc file, see the GitHub render of it [here](https://github.com/rubocop-hq/ruby-style-guide/blob/master/README.adoc) and search for 'scans a file for'.

The text is:
```
scans a file for `=begin` and `=end{=begin...=end@{=begin` pairs
```

Not quite sure what the intent is, maybe it's correct...

**Comment by bbatsov** [comment]
I think I just copied this from the RD docs way back.

**Comment by MSP-Greg** [comment]
@bbatsov

Understandable.  It's a large document.  I generated a new copy and something got confused and it rendered everything after that as a monospace font...  See PR https://github.com/rubocop-hq/ruby-style-guide/pull/830.

**Comment by bbatsov** [comment]
For the record - I found I had copied this from https://ruby-doc.com/docs/ProgrammingRuby/html/rdtool.html I'm assuming means to say that the markers can be nested. Anyways, not a big deal.
