### ISSUE TITLE
Typo in loop with break?

### ISSUE THREAD

**Issue by SinnahSaint** [rubocop-hq/ruby-style-guide#831]
In [Loop with Break](https://github.com/rubocop-hq/ruby-style-guide#loop-with-break) the code says:

`# bad
begin
  puts val
  val += 1
end while val < 0`

`# good
loop do
  puts val
  val += 1
  break unless val < 0
end `

And to me it seems they aren’t doing the same thing and one of the “val < 0” should be a “val > 0” because one is while and the other is unless.

**Comment by marcandre** [comment]
But it's `break unless` vs `[continue] while`
