### ISSUE TITLE
Compact case statements: is there a way to enforce single-line when?

### ISSUE THREAD

**Issue by dmolesUC** [rubocop-hq/ruby-style-guide#860]
Given:

```ruby
case foo
when 1
  bar
when 2
  baz
else
  qux
end
```

it would be nice to be able to autocorrect it to:

```ruby
case foo
when 1 then bar
when 2 then baz
else qux
end
```

**Comment by marcandre** [comment]
I don't think there's a cop to do that, but it should be pretty easy to write your own...

**Comment by bbatsov** [comment]
This seems like an issue for RuboCop, though, not for the style guide.

**Comment by marcandre** [comment]
Oh, indeed. Maybe I misread?

**Comment by dmolesUC** [comment]
Yep, my mistake, sorry. I'll close this one and re-file it over there.
